In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
dataset = pd.read_csv('Target 1 to 5 Cessna CJ 2  ATR 42 PC 12 PC 24 Beechcraft  06 Apr 24.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

Logistic Regression

In [14]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression()

In [16]:
y_pred = classifier.predict(X_test)

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[181  54  41  32  66]
 [  0 349 297  37  23]
 [  3 268 741  72  26]
 [ 73  69  71 150  30]
 [ 58  26 122  47 159]]


0.5275459098497496

K Nearest Neighbors(KNN)

In [22]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [24]:
y_pred = classifier.predict(X_test)

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[347  14   2  10   1]
 [  3 678  21   3   1]
 [  7  86 991  10  16]
 [ 20  24  26 307  16]
 [ 14  20  24  14 340]]


0.8891485809682804

Support Vector Machine

In [29]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear')
classifier.fit(X_train, y_train)

SVC(kernel='linear')

In [31]:
y_pred = classifier.predict(X_test)

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[209  67  26  37  35]
 [  2 524 130  36  14]
 [  5 426 586  70  23]
 [ 53  78  65 174  23]
 [ 46  87  72  42 165]]


0.5535893155258764

Kernel SVM

In [35]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf')
classifier.fit(X_train, y_train)

SVC()

In [37]:
y_pred = classifier.predict(X_test)

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[294  28   8  28  16]
 [  2 602  81   2  19]
 [  5 121 954  14  16]
 [ 26  18  76 231  42]
 [  1  36  85   8 282]]


0.7889816360601002

Naive Bayes

In [43]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [45]:
y_pred = classifier.predict(X_test)

In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[197  80  26  39  32]
 [  2 514 142  24  24]
 [ 25 339 629  17 100]
 [ 45  89 109  92  58]
 [ 37 102  93   0 180]]


0.5382303839732888

Decision Tree Classifier

In [51]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy')
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [53]:
y_pred = classifier.predict(X_test)

In [55]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[331   2  11  20  10]
 [  9 587  92  12   6]
 [ 11  55 978  20  46]
 [ 25  12  27 311  18]
 [ 10   6  21  47 328]]


0.8464106844741235

Random Forest Classifier


In [60]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion='entropy')
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [62]:
y_pred = classifier.predict(X_test)

In [64]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 359    0    4    5    6]
 [   1  690   12    2    1]
 [   0   29 1074    5    2]
 [  17    6   16  345    9]
 [   4    6   11    4  387]]


0.9532554257095158